name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SIGN_AND_NOTARIZE: false
  DATE_TIME1: '$(date +"%Y-%m-%d %H:%M:%S")'
  DATE_TIME2: $(date +"%Y-%m-%d %H:%M:%S")

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.17.x'

      - name: Export version as variable
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Current version: $VERSION"
          echo "EP_DRAFT=true" >> "$GITHUB_ENV"
          echo "electron-publish will release a draft"
        shell: bash

      - name: Install Dependencies
        run: |
          npm install npm@8.15.0 -g
          npm ci

      - name: Build Project
        run: npm run build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}.$(date +"%Y%m%d%H%M%S")

      - name: Install the Apple certificate and api key
        if: ${{ runner.os == 'macOS' && env.SIGN_AND_NOTARIZE == 'true' }}
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          API_KEY_PATH=$RUNNER_TEMP/auth_key.p8
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and api key from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo "CSC_LINK=$CERTIFICATE_PATH" >> "$GITHUB_ENV"
          echo "CSC_KEY_PASSWORD=$P12_PASSWORD" >> "$GITHUB_ENV"
          echo -n "$API_KEY_BASE64" | base64 --decode -o $API_KEY_PATH
          echo "APPLE_API_KEY=$API_KEY_PATH" >> "$GITHUB_ENV"

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build Windows App
        if: ${{ runner.os == 'Windows' }}
        run: npm run dist

      - name: Build Linux App
        if: ${{ runner.os == 'Linux' }}
        run: npm run dist-linux

      - name: Build macOS App
        if: ${{ runner.os == 'macOS' }}
        run: npm run dist-mac

  # TODO: adjust release name to like v1.2.3.202404011200
  # tag_name: v${{ env.VERSION }}.$(date +"%Y%m%d%H%M%S")
  # TODO: adjust electron publish release type to draft
  # TODO: adjust electron bundle files version name to like v1.2.3.202404011200
