name: Build
on:
  workflow_dispatch:
  pull_request:
      types:
        - closed
  push:
    branches: [main]
# develop pushes and repository_dispatch handled in build_develop.yaml
env:
  # These must be set for fetchdep.sh to get the right branch
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.x'

      - name: Export version to variable
        run: |
          npm install npm@8.15.0 -g
          npm install --registry=https://registry.npmjs.org/
          node getVersion.js
          export VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash
      
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ env.VERSION }}
      

      - name: Install Dependencies&&Build
        run: |
          npm run build
          
          if [ "$RUNNER_OS" == "Windows" ]; then
          sh build.sh

          fi
          if [ "$RUNNER_OS" == "Linux" ]; then
          sh build-linux.sh
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
          sh build-mac.sh
          fi
        shell: bash

      # - name: Release
      #   uses: softprops/action-gh-release@v0.1.15
      #   with:
      #     tag_name: v${{ env.VERSION }}
      #     files: |
      #      dist/Helium OS-${{ env.VERSION }}.dmg
      #      dist/Helium OS-${{ env.VERSION }}-mac.zip
      #      dist/Helium OS-${{ env.VERSION }}.dmg.blockmap
      #      dist/Helium OS-${{ env.VERSION }}-mac.zip.blockmap
      #      dist/latest-mac.yml
      #      dist/Helium OS Setup ${{ env.VERSION }}.exe
      #      dist/Helium OS Setup ${{ env.VERSION }}.exe.blockmap
      #      dist/latest.yml
      #      dist/Helium OS-${{ env.VERSION }}.AppImage
      #      dist/Helium OS-${{ env.VERSION }}.zip
